services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: wine-postgres
    environment:
      POSTGRES_USER: wine
      POSTGRES_PASSWORD: wine
      POSTGRES_DB: wine_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: