[project]
name = "winerecommender"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Daniel Kim", email = "dhjkim2001@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.143.0",
    "logging>=0.4.9.6",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "psycopg>=3.3.6",
    "pydantic>=2.14.0",
    "requests>=2.34.2",
    "sentence-transformers>=6.1.0",
    "tqdm>=4.70.1",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
]

[project.scripts]
winerecommender = "winerecommender:app"

[build-system]
requires = ["uv_build>=0.12.24,<0.13.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
